name: ARXIV Papers Daily on Feishu

on:
  schedule:
    - cron: '50 11 * * *'  # 每天UTC时间8:30运行（北京时间16:30）

jobs:
  send-papers:
    name: Fetch and Send Arxiv Papers
    runs-on: ubuntu-latest
    steps:
      - name: Arxiv to Feishu
        uses: junka/arxiv_feishu_bot_action@main
        with:
          keyword: 'CVPR'  # 改为你的领域关键词（如：LLM, Computer Vision等）
          webhook: ${{ https://open.feishu.cn/open-apis/bot/v2/hook/e6a8fec2-23bb-4736-99f5-b7ea02fd3b5d }}
          signkey: ${{ lLChRgE8fHBmm7LhPVoYnOIhHeTt6CLN }}
